version: '3'
services:
    web:
        container_name: Web
        build:
            context: ./
            dockerfile: ./conf/Dockerfile
        ports:
            - '8282:80'
        volumes:
            - './conf/sri.asir4all.ss.conf:/etc/apache2/sites-enabled/000-default.conf'
            - './conf/claves_digest.txt:/etc/apache2/claves_digest.txt'
            - './conf/clavesbasicas:/etc/apache2/clavesbasicas' 
            - './web/blog/:/var/www/'

